### PR TITLE
add basic authorization support

### PR DESCRIPTION
**Pull request by JaSei**

### CODE REVIEW

**Comment by JaSei** [comment]
Sorry to big vendor change... I like the assert test framework and I don't know how added to vendor. I use `go dep` and works well... But `go dep` probably actualize some dependency... If should be problem, I can try rewrite tests to don't using assert test framework... But I use this adapter and works well with my vendor changes....

**Comment by Thib17** [comment]
Interesting feature. Thanks, @JaSei 

But I do not think this should be a breaking change on existing flags, but a new flag to set user info (could be -graphite-user ). What do you think ?

And might be good to split the PR in two in order to discuss the govendor/godep change in an other PR. In the meantime you can run `govendor fetch github.com/stretchr/testify/assert` where `govendor` is your govendor bin (just do 'go get -u github.com/kardianos/govendor' then 'go install github.com/kardianos/govendor' and the bin should be in your $GOPATH/bin)

**Comment by JaSei** [comment]
This change works well with `-graphite-url http://localhost:8080/` or `-graphite-url localhost:8080` user info is optional...
I saw `// TODO (t.chataigner) Add support for basic auth + proxy` comment and implement with this PR first part (basic auth support) :wink:
Your are right with split this with new dependency management... I do it...

Thanks

**Comment by JaSei** [comment]
Now should be PR about  userinfo support only..

**Comment by iksaif** [comment]
Looks like travis isn't happy

**Pull request closed without merging**
